# 🔍 Módulo 5: Herramientas de Investigación
### Javier Orduz

[mywebsiteBDG]:https://img.shields.io/badge/website-jaorduz.github.io-0abeeb?style=plastic
[mywebsite]: https://jaorduz.github.io/

[mygithubBDG-jaorduz]: https://img.shields.io/badge/jaorduz-repos-blue?logo=github&label=jaorduz&style=plastic
[mygithub-jaorduz]: https://github.com/jaorduz/

[mygithubBDG-jaorduc]: https://img.shields.io/badge/jaorduc-repos-blue?logo=github&label=jaorduc&style=plastic 
[mygithub-jaorduc]: https://github.com/jaorduc/

[myXprofileBDG]: https://img.shields.io/static/v1?label=Follow&message=jaorduc&color=2ea44f&style=plastic&logo=X&logoColor=black
[myXprofile]:https://twitter.com/jaorduc

[![website - jaorduz.github.io][mywebsiteBDG]][mywebsite]
[![Github][mygithubBDG-jaorduz]][mygithub-jaorduz]
[![Github][mygithubBDG-jaorduc]][mygithub-jaorduc]
[![Follow @jaorduc][myXprofileBDG]][myXprofile]

![Version](https://img.shields.io/badge/version-1.0.0-blue)
![Python](https://img.shields.io/badge/python-3.11-blue)
![License](https://img.shields.io/badge/license-MIT-green)
![Status](https://img.shields.io/badge/status-stable-success)

---

*@Javier Orduz*

---
This notebook walks through the foundational concepts of research tools.

In [1]:
import pandas as pd
import numpy as np

# Load the research data
df = pd.read_csv('../data/research_data.csv')
df.head()

   id     name  value category
0   1  Sample1    100    TypeA
1   2  Sample2    150    TypeB
2   3  Sample3    120    TypeA
3   4  Sample4    180    TypeB
4   5  Sample5    110    TypeA

## Explore the Data

In [3]:
df.shape

(5, 4)

In [4]:
df.columns

Index(['id', 'name', 'value', 'category'], dtype='object')

In [5]:
# Display basic statistics
df.describe()

             id       value
count  5.000000    5.000000
mean   3.000000  132.000000
std    1.581139   32.710854
min    1.000000  100.000000
25%    2.000000  110.000000
50%    3.000000  120.000000
75%    4.000000  150.000000
max    5.000000  180.000000